name: Publish Docker branch image (edge)

on:
  schedule:
    - cron: '0 6 * * *' # At 06:00
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy_edge.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  push_to_registry:
    name: Push Docker branch image (edge)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ams21/cppcheck
            ghcr.io/ams21/cppcheck
          flavor: |
            latest=false
            prefix=
            suffix=
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=edge

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./
          build-args: "VERSION=main"
          push: true
          platforms: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x"
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
